name: elo_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_cart: ^0.0.9
  flutter_native_splash: ^2.4.3
  get: ^4.6.6
  http: ^1.2.2
  introduction_screen: ^3.1.14
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_native_splash:
  image: assets/elologo.png
  color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/elologo.png
    - assets/ecommerce1.png
    - assets/ecommerce2.png
    - assets/ecommerce3.png
